### ISSUE TITLE
Comment popup stays open after leaving screen

### ISSUE THREAD

**Issue by pairic1** [mellis3/prototype#3]
If you have a comment open and click on a hotspot on accident while trying to close the comment window, you'll leave the current screen but the comment window stays open. Would be useful if the hotspots didn't take you anywhere while the comment window is open. It would also be useful to have an "X" at the top right of the comment window. Maybe hanging off the corner?

**Comment by pairic1** [comment]
Or the comment window could just close when you leave the current screen.

**Comment by mellis3** [comment]
Added a function to close any open comments when switching slides. Fixed with this commit: https://github.com/mellis3/prototype/commit/4e4cd4b67b04849d834c14a450e7cd169601a50a
