### ISSUE TITLE
Global hotspot missing from list

### ISSUE THREAD

**Issue by pairic1** [mellis3/prototype#7]
I've seen this global hotspot on a screen, but it's not on the list to add: issue_level_EC_concurrence

**Comment by mellis3** [comment]
for whatever reason i named the global hotspot "issue_level_EC_approval" not concurrence. But to alleviate that i added some additional details about the hotspot under the name in the list. Added that with this commit: https://github.com/mellis3/prototype/commit/301eac7c5c158b87515f4c488416db14e98dd0e4
