### ISSUE TITLE
Adding global hotspot crashes the prototype

### ISSUE THREAD

**Issue by pairic1** [mellis3/prototype#8]
After adding a global hotspot, the clickthrough quits working. The hotspots don't work or it gets stuck on the loading screen.

Console:
![Screen Shot 2019-12-18 at 9 08 05 AM](https://user-images.githubusercontent.com/20744612/71092803-f09e0700-2175-11ea-89c9-737935a38577.png)

**Comment by mellis3** [comment]
@pairic1 adding a global hotspot seems to work for me. Can you provide more details about how this happened? Which slide, where were you trying to put it etc?

**Comment by pairic1** [comment]
I can't find the slide anymore, I think it was a matter of not refreshing after adding the hotspot.
